services:
  db:
    image: postgres
    restart: always
    container_name: TasksApp
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: ${DATASOURCE_DATABASE}
    ports:
      - "${DATASOURCE_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3


  # Meilisearch setup
  meilisearch:
    image: getmeili/meilisearch:v1.10 # Replace with the latest version
    environment:
      # Set the master key for production
      MEILI_MASTER_KEY: ${MEILI_MASTER}
      # Use production mode
      MEILI_ENV: ${MEILI_ENV}
    volumes:
      - meili-data:/meili_data
    ports:
      - "7700:7700"


volumes:
  db-data:
  meili-data:
