### Send POST request with json body
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "name": "danielle Merveille",
  "email": "daniella@gmail.fr",
  "password": "Type@@2012"
}


### Send POST request with json body
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "helni@gmail.fr",
  "password": "Type@@2012"
}
