### LOGIN
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "helni@gmail.fr",
  "password": "Type@@2012"
}

### CREATE
POST http://localhost:3000/api/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiaGVsbmlAZ21haWwuZnIiLCJpYXQiOjE3MjgxNzUzOTIsImV4cCI6MTcyODE3ODk5MiwiYXVkIjoibG9jYWxob3N0OjMwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAifQ.Yt0SFg9LLPNLSDhjDz0SnUnKBRAUbMa2iO3R9n9O0Y4
Content-Type: application/json

{
  "title": "Import Path 12 ",
  "description": "Learn git 2"
}

### UPDATE
PUT http://localhost:3000/api/todos/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiaGVsbmlAZ21haWwuZnIiLCJpYXQiOjE3MjgxNzUzOTIsImV4cCI6MTcyODE3ODk5MiwiYXVkIjoibG9jYWxob3N0OjMwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAifQ.Yt0SFg9LLPNLSDhjDz0SnUnKBRAUbMa2iO3R9n9O0Y4
Content-Type: application/json

{
  "title": "Buy 4 groceries",
  "description": "Buy milk, eggs, and bread"
}

### DELETE
DELETE http://localhost:3000/api/todos/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiaGVsbmlAZ21haWwuZnIiLCJpYXQiOjE3MjgxNzUzOTIsImV4cCI6MTcyODE3ODk5MiwiYXVkIjoibG9jYWxob3N0OjMwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAifQ.Yt0SFg9LLPNLSDhjDz0SnUnKBRAUbMa2iO3R9n9O0Y4
Accept: application/json

### GET ALL
GET http://localhost:3000/api/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiaGVsbmlAZ21haWwuZnIiLCJpYXQiOjE3MjgxNzkwOTIsImV4cCI6MTcyODE4MjY5MiwiYXVkIjoibG9jYWxob3N0OjMwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAifQ.tIsrcfIfL1c73mSWU5oDNVfxteIYjWmOXIzFOOIOFYU
Accept: application/json

### SEARCH
GET http://localhost:3000/api/todos/search?search=important
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiaGVsbmlAZ21haWwuZnIiLCJpYXQiOjE3MjgxNzk0NjMsImV4cCI6MTcyODE4MzA2MywiYXVkIjoibG9jYWxob3N0OjMwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAifQ.m0wi46L1MH4X3SHyJa-mQ_hGJcHDIbfBYkI5Mil09Lg
Accept: application/json


### GET ALL WITH LIMIT
GET http://localhost:3000/api/todos?page=1&limit=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiaGVsbmlAZ21haWwuZnIiLCJpYXQiOjE3MjgxNzUzOTIsImV4cCI6MTcyODE3ODk5MiwiYXVkIjoibG9jYWxob3N0OjMwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAifQ.Yt0SFg9LLPNLSDhjDz0SnUnKBRAUbMa2iO3R9n9O0Y4
Accept: application/json



